from app.resources.reps import router as reps
from app.resources.reports import router as reports
from app.resources.branches import router as branches
from app.resources.download import router as downloads
from app.resources.locations import router as locations
from app.resources.customers import router as customers
from app.resources.commissions import router as commissions
from app.resources.submissions import router as submissions
from app.resources.id_str_mapping import router as mappings
from app.resources.manufacturers import router as manufacturers
from app.resources.relationships import router as relationships
