from app.resources.commissions import router as commissions
from app.resources.branches import router as branches
from app.resources.customers import router as customers
from app.resources.manufacturers import router as manufacturers
from app.resources.mappings import router as mappings
from app.resources.reps import router as reps
from app.resources.submissions import router as submissions
from app.resources.cities import router as cities
from app.resources.states import router as states
from app.resources.relationships import router as relationships
